# PolyEntropy Pro - Report Generator
import json
import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PolyEntropy Pro Report</title>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; background: #1a1a2e; color: #e0e0e0; margin: 0; padding: 20px; }
h1 { color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }
h2 { color: #7ec8e3; margin-top: 30px; }
.verdict-box { padding: 15px; border-radius: 8px; margin: 20px 0; font-size: 1.3em; font-weight: bold; }
.verdict-clean { background: #1a3a1a; border: 2px solid #4caf50; color: #4caf50; }
.verdict-suspicious { background: #3a2a00; border: 2px solid #ff9800; color: #ff9800; }
.verdict-likely { background: #3a1a00; border: 2px solid #ff5722; color: #ff5722; }
.verdict-strong { background: #3a0000; border: 2px solid #f44336; color: #f44336; }
table { width: 100%; border-collapse: collapse; margin: 10px 0; }
th { background: #16213e; color: #00d4ff; padding: 8px 12px; text-align: left; }
td { padding: 7px 12px; border-bottom: 1px solid #2a2a4a; }
tr:hover td { background: #1e1e3a; }
.entropy-bar-container { display: flex; align-items: center; gap: 8px; }
.entropy-bar { height: 16px; border-radius: 3px; display: inline-block; }
.low { background: #4caf50; }
.medium { background: #ff9800; }
.high { background: #f44336; }
.indicator-list { list-style: none; padding: 0; }
.indicator-list li { padding: 6px 10px; margin: 4px 0; border-radius: 4px; background: #16213e; }
.indicator-list li.bad { border-left: 4px solid #f44336; }
.indicator-list li.warn { border-left: 4px solid #ff9800; }
.indicator-list li.ok { border-left: 4px solid #4caf50; }
.meta { color: #888; font-size: 0.9em; }
code { background: #0f0f23; padding: 2px 6px; border-radius: 3px; font-size: 0.85em; }
</style>
</head>
<body>
<h1>&#x1F50D; PolyEntropy Pro Analysis Report</h1>
<p class="meta">File: <strong>{{ filename }}</strong> | Type: {{ file_type }} | Arch: {{ arch }} | Date: {{ date }}</p>

<div class="verdict-box verdict-{{ verdict_class }}">
  Verdict: {{ verdict }} &mdash; Confidence Score: {{ score }}/100
</div>

<h2>Section Entropy</h2>
<table>
  <tr><th>Section</th><th>Entropy</th><th>Visualization</th><th>Permissions</th><th>Size</th></tr>
  {% for sec in sections %}
  <tr>
    <td><code>{{ sec.name }}</code></td>
    <td>{{ "%.3f"|format(sec.entropy) }}</td>
    <td>
      <div class="entropy-bar-container">
        <div class="entropy-bar {{ sec.entropy_class }}" style="width: {{ (sec.entropy / 8 * 200)|int }}px"></div>
        {{ "%.1f"|format(sec.entropy) }}
      </div>
    </td>
    <td>{{ sec.permissions }}</td>
    <td>{{ sec.size }}</td>
  </tr>
  {% endfor %}
</table>

<h2>Indicators</h2>
<ul class="indicator-list">
  {% for ind in indicators %}
  <li class="{{ ind.level }}">{{ ind.text }}</li>
  {% endfor %}
</ul>

{% if suspicious_imports %}
<h2>Suspicious Imports</h2>
<ul class="indicator-list">
  {% for imp in suspicious_imports %}
  <li class="bad">{{ imp }}</li>
  {% endfor %}
</ul>
{% endif %}

{% if crypto_constants %}
<h2>Crypto Constants Found</h2>
<table>
  <tr><th>Offset</th><th>Value</th><th>Name</th><th>Endian</th></tr>
  {% for cc in crypto_constants %}
  <tr>
    <td><code>0x{{ "%x"|format(cc.offset) }}</code></td>
    <td><code>0x{{ "%08x"|format(cc.value) }}</code></td>
    <td>{{ cc.name }}</td>
    <td>{{ cc.endian }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if decryptor_loops %}
<h2>Decryptor Loops Detected</h2>
<table>
  <tr><th>Offset</th><th>Type</th><th>Description</th></tr>
  {% for dl in decryptor_loops %}
  <tr>
    <td><code>0x{{ "%x"|format(dl.offset) }}</code></td>
    <td>{{ dl.type }}</td>
    <td>{{ dl.description }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

<h2>Summary</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Total Imports</td><td>{{ import_count }}</td></tr>
  <tr><td>Total Exports</td><td>{{ export_count }}</td></tr>
  <tr><td>RWX Sections</td><td>{{ rwx_sections|join(", ") or "None" }}</td></tr>
  <tr><td>Entry Point</td><td><code>0x{{ "%x"|format(entry_point) }}</code></td></tr>
  <tr><td>Entry Point Status</td><td>{{ ep_status }}</td></tr>
</table>

<p class="meta" style="margin-top:40px">Generated by PolyEntropy Pro</p>
</body>
</html>
"""


def _verdict_class(verdict: str) -> str:
    v = verdict.lower()
    if "strong" in v:
        return "strong"
    elif "likely" in v:
        return "likely"
    elif "suspicious" in v or "packed" in v:
        return "suspicious"
    return "clean"


def _entropy_class(e: float) -> str:
    if e < 5.0:
        return "low"
    elif e < 7.2:
        return "medium"
    return "high"


def generate_json(results: dict) -> str:
    """Generate JSON report string."""
    # Make it serializable
    safe = json.loads(json.dumps(results, default=str))
    return json.dumps(safe, indent=2)


def generate_html(results: dict) -> str:
    """Generate HTML report string using Jinja2 or fallback."""
    try:
        from jinja2 import Template
        tmpl = Template(HTML_TEMPLATE)
        return tmpl.render(**_build_template_vars(results))
    except ImportError:
        return _generate_html_fallback(results)


def _build_template_vars(results: dict) -> dict:
    from entropy import entropy_color  # noqa
    sections = []
    for sec in results.get("sections", []):
        e = sec.get("entropy", 0.0)
        sections.append({
            "name": sec.get("name", "?"),
            "entropy": e,
            "entropy_class": _entropy_class(e),
            "permissions": sec.get("permissions", "---"),
            "size": sec.get("size", 0),
        })

    indicators = []
    for ind in results.get("indicators", []):
        level = "bad" if ind.get("score", 0) > 10 else ("warn" if ind.get("score", 0) > 0 else "ok")
        indicators.append({"text": ind.get("text", ""), "level": level})

    crypto_constants = []
    for cc in results.get("crypto_constants", []):
        crypto_constants.append({
            "offset": cc[0],
            "value": cc[1],
            "name": cc[2],
            "endian": cc[3] if len(cc) > 3 else "",
        })

    return {
        "filename": results.get("filename", "Unknown"),
        "file_type": results.get("file_type", "Unknown"),
        "arch": results.get("arch", "Unknown"),
        "date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "verdict": results.get("verdict", "Unknown"),
        "verdict_class": _verdict_class(results.get("verdict", "")),
        "score": results.get("score", 0),
        "sections": sections,
        "indicators": indicators,
        "suspicious_imports": results.get("suspicious_imports", []),
        "crypto_constants": crypto_constants,
        "decryptor_loops": results.get("decryptor_loops", []),
        "import_count": results.get("import_count", 0),
        "export_count": results.get("export_count", 0),
        "rwx_sections": results.get("rwx_sections", []),
        "entry_point": results.get("entry_point", 0),
        "ep_status": results.get("ep_status", ""),
    }


def _generate_html_fallback(results: dict) -> str:
    """Simple HTML fallback if Jinja2 not available."""
    v = results.get("verdict", "Unknown")
    s = results.get("score", 0)
    fn = results.get("filename", "Unknown")
    lines = [
        "<!DOCTYPE html><html><body>",
        f"<h1>PolyEntropy Pro Report</h1>",
        f"<p>File: {fn}</p>",
        f"<p><b>Verdict: {v} (Score: {s}/100)</b></p>",
        "<h2>Sections</h2><table border='1'>",
        "<tr><th>Name</th><th>Entropy</th><th>Perms</th></tr>",
    ]
    for sec in results.get("sections", []):
        lines.append(
            f"<tr><td>{sec.get('name')}</td>"
            f"<td>{sec.get('entropy', 0):.3f}</td>"
            f"<td>{sec.get('permissions', '')}</td></tr>"
        )
    lines.append("</table>")
    lines.append("<h2>Indicators</h2><ul>")
    for ind in results.get("indicators", []):
        lines.append(f"<li>{ind.get('text', '')}</li>")
    lines.append("</ul></body></html>")
    return "\n".join(lines)
